// Generated by https://quicktype.io

export interface LoginResponse {
    user:  User;
    token: string;
}

export interface User {
    _id:             string;
    dni:             string;
    nombre:          string;
    apellidos:       string;
    fechaNacimiento: Date;
    telefono:        number;
    correo:          string;
    repetirCorreo:   string;
    direccion:       string;
    estado:          string;
    fechaIni:        Date;
    fechaFin?:       Date;
    superUsuario:    boolean;
}
